---
name: On Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Tests
        uses: ./.github/actions/tests